<div id="feedbackco-widget">
    <button id="feedbackco-button">Feedback</button>
    <div class="feedbackco-form-container" style="display: none;">
        <div class="feedbackco-form">
            <h3>Send us your feedback</h3>
            <form class="feedbackco-form-element">
                <div class="feedbackco-field">
                    <label for="feedbackco-name-widget">Name</label>
                    <input type="text" id="feedbackco-name-widget" name="user_name" required>
                </div>
                <div class="feedbackco-field">
                    <label for="feedbackco-email-widget">Email</label>
                    <input type="email" id="feedbackco-email-widget" name="user_email" required>
                </div>
                <div class="feedbackco-field">
                    <label>Rating</label>
                    <div class="feedbackco-rating">
                        <!-- Stars will be generated by JavaScript -->
                    </div>
                </div>
                <div class="feedbackco-field">
                    <label for="feedbackco-message-widget">Message</label>
                    <textarea id="feedbackco-message-widget" name="message" required></textarea>
                </div>
                <button type="submit" class="feedbackco-submit">Submit</button>
                <button type="button" class="feedbackco-cancel">Cancel</button>
            </form>
            <div class="feedbackco-thank-you" style="display: none;">
                <h3>Thank you for your feedback!</h3>
                <p>We appreciate your input.</p>
                <button class="feedbackco-close">Close</button>
            </div>
        </div>
    </div>
</div>
