<div class="feedbackco-form-container" data-form-id="<?php echo esc_attr($id); ?>">
    <div class="feedbackco-form">
        <h3><?php echo esc_html($title); ?></h3>
        <form class="feedbackco-form-element">
            <div class="feedbackco-field">
                <label for="feedbackco-name-<?php echo esc_attr($id); ?>">Name</label>
                <input type="text" id="feedbackco-name-<?php echo esc_attr($id); ?>" name="user_name" required>
            </div>
            <div class="feedbackco-field">
                <label for="feedbackco-email-<?php echo esc_attr($id); ?>">Email</label>
                <input type="email" id="feedbackco-email-<?php echo esc_attr($id); ?>" name="user_email" required>
            </div>
            <div class="feedbackco-field">
                <label>Rating</label>
                <div class="feedbackco-rating">
                    <!-- Stars will be generated by JavaScript -->
                </div>
            </div>
            <div class="feedbackco-field">
                <label for="feedbackco-message-<?php echo esc_attr($id); ?>">Message</label>
                <textarea id="feedbackco-message-<?php echo esc_attr($id); ?>" name="message" required></textarea>
            </div>
            <button type="submit" class="feedbackco-submit"><?php echo esc_html($button_text); ?></button>
        </form>
        <div class="feedbackco-thank-you" style="display: none;">
            <h3>Thank you for your feedback!</h3>
            <p>We appreciate your input.</p>
            <button class="feedbackco-close">Close</button>
        </div>
    </div>
</div>
