<div id="feedbackco-widget">
    <button id="feedbackco-button">Feedback</button>
    <div id="feedbackco-form-container" style="display: none;">
        <div id="feedbackco-form">
            <h3>Send us your feedback</h3>
            <form id="feedbackco-form-element">
                <div class="feedbackco-field">
                    <label for="feedbackco-name">Name</label>
                    <input type="text" id="feedbackco-name" name="user_name" required>
                </div>
                <div class="feedbackco-field">
                    <label for="feedbackco-email">Email</label>
                    <input type="email" id="feedbackco-email" name="user_email" required>
                </div>
                <div class="feedbackco-field">
                    <label for="feedbackco-rating">Rating</label>
                    <div id="feedbackco-rating">
                        <!-- Stars will be generated by JS -->
                    </div>
                </div>
                <div class="feedbackco-field">
                    <label for="feedbackco-message">Message</label>
                    <textarea id="feedbackco-message" name="message" required></textarea>
                </div>
                <button type="submit" id="feedbackco-submit">Submit</button>
                <button type="button" id="feedbackco-cancel">Cancel</button>
            </form>
        </div>
    </div>
</div>
