<?php
$options = array(
    'display_mode' => get_option('feedbackco_shortcode_display_mode', 'inline'),
);



$categories = get_option('feedbackco_feedback_categories', array());
?>

<div id="feedbackco-shortcode-form">
<div class="feedbackco-form-shortcode">
    <form id="feedbackco-form-element-shortcode">

        <div class="feedbackco-field">
            <label for="feedbackco-name">Name</label>
            <input type="text" id="feedbackco-name" name="user_name" required>
        </div>
        <div class="feedbackco-field">
            <label for="feedbackco-email">Email</label>
            <input type="email" id="feedbackco-email" name="user_email" required>
        </div>
        <div class="feedbackco-field">
            <label>Rating</label>
            <div class="feedbackco-rating">
                <!-- Stars will be generated by JavaScript -->
            </div>
        </div>

        <?php if (!empty($categories)): ?>
        <div class="feedbackco-field">
            <label for="feedbackco-category">Category</label>
            <select id="feedbackco-category" name="category" required>
                <option value="">Select a category</option>
                <?php foreach ($categories as $category): ?>
                    <option value="<?php echo esc_attr($category); ?>"><?php echo esc_html($category); ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <?php endif; ?>

        <div class="feedbackco-field">
            <label for="feedbackco-message">Message</label>
            <textarea id="feedbackco-message" name="message" required></textarea>
        </div>

        <div style="display:none;">
            <label for="feedbackco-website">Website</label>
            <input type="text" id="feedbackco-website" name="website" autocomplete="off">
        </div>

        <button type="submit" id="feedbackco-submit">Submit</button>

    </form>
    </div>
</div>
